[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.15"
via_ir = true
broadcast = 'records'
fs_permissions = [{ access = "read-write", path = "./" }]
ffi = true                                                # Enable FFI for reading superchain registry files in tasks' SignFromJson.s.sol, NestedSignFromJson.s.sol

remappings = [
  '@openzeppelin/contracts-upgradeable/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts-upgradeable/contracts/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
  '@base-contracts/=lib/base-contracts/',
  '@eth-optimism-bedrock/=lib/optimism/packages/contracts-bedrock/',
  '@rari-capital/solmate/=lib/solmate',
  '@eth-optimism-superchain-registry/=lib/superchain-registry/',
  'forge-std/=lib/forge-std/src/',
]

[profile.ci]
deny_warnings = true
